### ISSUE TITLE
Segfault on converstion to `mi/(h+m)`

### ISSUE THREAD

**Issue by flaviut** [Qalculate/libqalculate#445]
```
$ qalc
> 60mi/23h15min23s to mi/(h+m)
[1]    1221491 segmentation fault (core dumped)  qalc
$ qalc -v
4.2.0
```

seems to get stuck in an infinite recursion and segfault:

```
#1  0x00007ffff7e2487e in MathStructure::calculateRaiseExponent (this=0x7fffec16ca80, eo=..., mparent=0x0, index_this=1) at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:6611
#2  0x00007ffff7e11763 in MathStructure::merge_power (this=0x7fffec16c8b0, mstruct=..., eo=..., mparent=0x7fffec16c570, index_this=0, index_mstruct=<optimized out>)
    at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:3675
#3  0x00007ffff7e2487e in MathStructure::calculateRaiseExponent (this=0x7fffec16c570, eo=..., mparent=0x0, index_this=1) at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:6611
#4  0x00007ffff7e12b1d in MathStructure::merge_power (this=0x7fffec16c570, mstruct=..., eo=..., mparent=<optimized out>, index_this=0, index_mstruct=<optimized out>)
    at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:3702
#5  0x00007ffff7e2487e in MathStructure::calculateRaiseExponent (this=0x7fffec16c230, eo=..., mparent=0x0, index_this=1) at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:6611
#6  0x00007ffff7e12b1d in MathStructure::merge_power (this=0x7fffec16c230, mstruct=..., eo=..., mparent=<optimized out>, index_this=0, index_mstruct=<optimized out>)
    at /build/libqalculate/src/libqalculate-4.2.0/libqalculate/MathStructure-calculate.cc:3702
```

I'm on Arch Linux.

**Comment by hanna-kn** [comment]
Fixed.

Note that conversion to a unit expression with addition is not supported.
