### ISSUE TITLE
Crash in Number destructor 

### ISSUE THREAD

**Issue by dschopf** [Qalculate/libqalculate#551]
Hi, running the following code crashes 100% of the time for me:
```
#include <memory>
#include <libqalculate/qalculate.h>

int main() {
	auto calc{std::make_unique<Calculator>()};
	auto result{calc->calculate("55 to meter")};

	return 0;
}
```

Here is a backtrace without debug symbols:
```
#0  0x00007ffff76abf8c in mpfr_clear () from /usr/lib/libmpfr.so.6
#1  0x00007ffff76d86eb in mpfr_clears () from /usr/lib/libmpfr.so.6
#2  0x00007ffff7a0a38a in Number::~Number() () from /usr/lib/libqalculate.so.22
#3  0x00007ffff7a5a01c in MathStructure::~MathStructure() () from /usr/lib/libqalculate.so.22
#4  0x00007ffff79fefa0 in KnownVariable::~KnownVariable() () from /usr/lib/libqalculate.so.22
#5  0x00007ffff7a0284c in ?? () from /usr/lib/libqalculate.so.22
#6  0x00007ffff792b69f in Calculator::~Calculator() () from /usr/lib/libqalculate.so.22
#7  0x00007ffff792c4ee in Calculator::~Calculator() () from /usr/lib/libqalculate.so.22
#8  0x000055555555698c in std::default_delete<Calculator>::operator()(Calculator*) const ()
#9  0x0000555555556676 in std::unique_ptr<Calculator, std::default_delete<Calculator> >::~unique_ptr() ()
#10 0x000055555555639d in main ()
```

Issue seems to be related to units, `55 to hex` does not crash while `55 to meter` or `55 to joule` does crash.

**Comment by hanna-kn** [comment]
Fixed.

Temporary value were deleted both in destructor of DynamicVariable (parent of EVariable) and its parent KnownVariable. Since definitions were not loaded, no units were involved and part of "meter" were interpreted as the constant `e`.
